#!/bin/bash

bashful::begin() {
  local dir="$(dirname "${BASH_SOURCE}")"
  source "${dir}/flag-parsing-internal/flag-parsing-internal"
}

bashful::end() {
  # Variables
  unset -v OPTS
  unset -v NUM_OPT_ARGS
  unset -v NUM_POS_ARGS
  unset -v REQUIRED
  unset -v DEFAULT
  unset -v ACTION
  unset -v STORE
  unset -v INSTANCES
  unset -v POST_PARSE
  unset -v POS_ORDER
  
  unset -v ARG_VALUES
  unset -v OPT_COUNTS

  # Private functions
  unset -f parse

  unset -f register_opt_base
  unset -f register_opt_from_dict
  unset -f register_opt_from_line
  unset -f register_opt_value
  unset -f register_opt_bool_flag
  unset -f register_opt_with_arg
  unset -f register_opt_count
  unset -f register_pos

  unset -f consume_flag
  unset -f consume_pos

  unset -f validate_opts

  unset -f post_parse

  unset -f missing_args
  unset -f missing_required
  unset -f too_many_instances
  unset -f missing_pos_args
  unset -f too_many_pos_args
  unset -f missing_required_pos

  unset -f debug
  unset -f print_all
  unset -f print_arg
  unset -f copy_array
}

# Common post-parse callbacks
bashful::print_arg() {
  printf '%s\n%s\n' 'PRINTING' "$@"
}

bashful::save_to_global() {
  local -r name="$1"
  local -r val="$3"
  printf -v "${name}" "${val}"
}

